### ISSUE TITLE
Verify smart contracts on Etherscan

### ISSUE THREAD

**Issue by remote-gildor** [TCGV/DeFiOptions#4]
Hey Thomas,

Can you please verify the Kovan smart contracts on Etherscan, so that it's possible to interact with them via Etherscan? 🙂 

There's a really good Truffle plugin for that: https://github.com/rkalis/truffle-plugin-verify 

Here's a tutorial (it's very simple): https://kalis.me/verify-truffle-smart-contracts-etherscan/

**Comment by TCGV** [comment]
Hey gildor,

So these addresses are actually [Proxy](https://github.com/TCGV/DeFiOptions/blob/master/contracts/deployment/Proxy.sol) addresses deployed by the [Deployer](https://github.com/TCGV/DeFiOptions/blob/master/contracts/deployment/Deployer.sol) contract:

- **OptionsExchange**: 0xef1029a23cbaf78823a89b4f793c293163a65fcb
- **CreditToken**: 0x286e5ce4c2231279750aa79eff7c097f85e309e9
- **Linear Liquidity Pool**: 0x5e40a65621d14102e2fa532694bcd640bdd53cfb

I was able to verify their implementation addresses though (which should not be directly called since data storage happens in the Proxy, and the implementation contains only the logic to be executed, but no storage):

- **OptionsExchange**: 0x9db24ee5cba2972e1cbe061ba2a4d2427dc77b26
- **CreditToken**: 0xa0488f71bf637d5637121990ea26a1fe8d011cfc
- **Linear Liquidity Pool**: 0xf834Cb41AF96410C621E432118B4B0d90420e016

The price feed contracts are not proxied, so I was able to verify them as expected:

- **ETH/USD feed**: 0xb287A334718C976718F081d1060A84CbbCf5E0ba
- **BTC/USD feed**: 0x5Cb3e5A973cD838d46509EFf159011689A19772A

Regarding the **ERC20Mock** contract I was not able to verify it since it was deployed before a code refactor, so verification failed. But I could redeploy this contract for verifying it, just let me know if you need that.

**Comment by remote-gildor** [comment]
Ok, got it - all good so far 👍
